config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link href="https://code.jquery.com/mobile/1.4.5/jquery.mobile.structure-1.4.5.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
  <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
      <li class="divider"></li>
      <li><a href="#!">Log Out</a></li>
    </ul>

    <ul id="dropdown2" class="dropdown-content">
      <li class="divider"></li>
      <li><a href="#!">Log Out</a></li>
    </ul>

    <header>
      <nav class="brown lighten-4 z-depth-2">
        <div class="container">
          <div class="nav-wrapper">
            <a href="#!" class="brand-logo">Yang's Portfolio</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
              <li><a href="#">Projects</a></li>
              <li><a href="#">Sign Up</a></li>
              <li><a href="#">Log In</a></li>
              <!-- Dropdown Trigger -->
              <li><a class="dropdown-button" href="#!" data-activates="dropdown1">YANG LIU<i class="material-icons right">arrow_drop_down</i></a></li>

            </ul>
            <ul class="side-nav" id="mobile-demo">
              <li><a href="#">Projects</a></li>
              <li><a href="#">Sign Up</a></li>
              <li><a href="#">Log In</a></li>
              <!-- Dropdown Trigger -->
              <li><a class="dropdown-button" href="#!" data-activates="dropdown2">YANG LIU<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer class="page-footer brown lighten-4">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Yang's Portfolio</h5>
            <p class="grey-text text-lighten-4">Take action now if we do not want to be lost.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Social</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Github</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Qiita</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2020 Copyright Yang's Portfolio
        <%link_to "About Me", pages_about_path, :class => "grey-text text-lighten-4 right"%>
        </div>
      </div>
    </footer>
  </body>
  
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>